### ISSUE TITLE
file listed in the media-tv/popcorntime-bin/Manifest could not be found.

### ISSUE THREAD

**Issue by santoshkushwaha** [DevPump/gentoo-overlay#1]
The Manifest file for popcorntime-bin contains the digest and other details for the previous version '0.3.7.2'. The issue is that upon installing the latest package it complains following "file listed in the Manifest could not be found: /var/lib/layman/devpump-gor/media-tv/popcorntime-bin/ popcorntime-bin-0.3.7.2.ebuild".
However the problem resolves when removing the file details for v0.3.7.2 from the Manifest.
So can we get rid of them?

**Comment by DevPump** [comment]
Unneeded entries removed.
Thanks for the notice.
